language: node_js
node_js:
  - "10"
  - "12"
 
cache:
    directories:
        - "node_modules"
        
        
install:
  - npm run test:e2e
  
script: echo "npm test temporarily disabled"
  
servers:
  - 'docker'
 

after_success:
  - docker build -t nestjs-products-api .
  
before_deploy:
  - docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD" docker.io ;
  - docker tag nestjs-products-api $DOCKER_USERNAME/nestjs-products-api:latest
  
  
  
deploy:
    provider: script
    script: docker push $DOCKER_USERNAME/nestjs-products-api:latest ;
